services:
  db:
    container_name: orenoquiz_db_local
    image: postgres:15
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
volumes:
  db-store: